function filtered_super_loc_total = filterBadLocs(super_loc_total)
% filter bad localizations

valid = super_loc_total(:,3) > 20 ... % enough photons
    & super_loc_total(:,3) < 1e7 ...         % avoid divergence
    & super_loc_total(:,4) > 0 ...
    & super_loc_total(:,4) < 1e5 ...
    & super_loc_total(:,5) > 0.5 ...
    & super_loc_total(:,5) < 5 ...
    & super_loc_total(:,6) > 0 ...
    & super_loc_total(:,6) < 1;     % unreasonable uncertainty

n_before = size(super_loc_total,1);
filtered_super_loc_total = super_loc_total(valid,:);
n_after = size(filtered_super_loc_total,1);
fprintf('Filtered %d localizations out of %d (%.2f%%)\n', ...
n_before - n_after, n_before, ...
100*(n_before - n_after)/n_before);

end